# Generated by Django 4.2.1 on 2023-05-11 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "city",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "weather_condition",
                    models.CharField(
                        choices=[
                            ("Thunderstorm", "Thunderstorm"),
                            ("Drizzle", "Drizzle"),
                            ("Rain", "Rain"),
                            ("Snow", "Snow"),
                            ("Mist", "Mist"),
                            ("Smoke", "Smoke"),
                            ("Haze", "Haze"),
                            ("Dust", "Dust"),
                            ("Fog", "Fog"),
                            ("Sand", "Sand"),
                            ("Dust", "Dust"),
                            ("Ash", "Ash"),
                            ("Squall", "Squall"),
                            ("Tornado", "Tornado"),
                            ("Clear", "Clear"),
                            ("Clouds", "Clouds"),
                        ],
                        max_length=100,
                    ),
                ),
                ("weather_description", models.CharField(max_length=100, null=True)),
                ("temperature", models.FloatField()),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weathers",
                        to="weather.location",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("city", "latitude", "longitude"),
                name="unique_city_coordinates_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="weather",
            constraint=models.UniqueConstraint(
                fields=("location", "date"), name="unique_location_date_combination"
            ),
        ),
    ]
